# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /uio/hume/student-u83/carlosan/privat/in3160/oblig_10_system2/oblig_10_system2.srcs/sources_1/bd/tutorial_bd/ip/tutorial_bd_processing_system7_0_0/tutorial_bd_processing_system7_0_0.xci
# IP: The module: 'tutorial_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /uio/hume/student-u83/carlosan/privat/in3160/oblig_10_system2/oblig_10_system2.gen/sources_1/bd/tutorial_bd/ip/tutorial_bd_processing_system7_0_0/tutorial_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /uio/hume/student-u83/carlosan/privat/in3160/oblig_10_system2/oblig_10_system2.srcs/sources_1/bd/tutorial_bd/ip/tutorial_bd_processing_system7_0_0/tutorial_bd_processing_system7_0_0.xci
# IP: The module: 'tutorial_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /uio/hume/student-u83/carlosan/privat/in3160/oblig_10_system2/oblig_10_system2.gen/sources_1/bd/tutorial_bd/ip/tutorial_bd_processing_system7_0_0/tutorial_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
